api_key = "your_DeepL_api_key"

[glossaries.internet_computer]
"Internet Computer" = "Internet Computer"
"internet computer" = "internet computer"
"Internet Computer Protocol" = "Internet Computer Protocol"
"internet computer protocol" = "internet computer protocol"
"query call" = "クエリーコール"
"update call" = "アップデートコール"
"actor" = "actor"
"Actor" = "Actor"
"canister" = "canister"
"canisters" = "canisters"
"Canister" = "canister"
"Canisters" = "canisters"
"minting" = "発行"
"standard" = "規格"
"burn" = "バーン"
"dapp" = "Dapp"
"Architecture" = "アーキテクチャ"
"state" = "ステート"
"principal" = "プリンシパル"
