api_key = "your_DeepL_api_key"

[glossaries.internet_computer]
"query call" = "クエリーコール"
"update call" = "アップデートコール"
"minting" = "発行"
"standard" = "規格"
"burn" = "バーン"
"Architecture" = "アーキテクチャ"
"state" = "ステート"
"principal" = "プリンシパル"

[ignores]
# ignoreグループ名 = [単語, 単語, ...]
internet_computer = [
  "Internet Computer( Protocol)?",
  "Actor",
  "Canister(s)?",
  "Dapp(s)?",
  "cycle(s)?",
  "Dfinity",
  "Discord",
  "Motoko",
  "Network Nervous System",
  "Neuron",
  "WebAssembly",
]
